---
apiVersion: v1
kind: Namespace
metadata:
  name: kloudknox
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    boanlab.com/app: kloudknox-operator
  name: kloudknox-operator
  namespace: kloudknox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kloudknox-operator-role
rules:
- apiGroups:
  - security.boanlab.com
  resources:
  - kloudknoxpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.boanlab.com
  resources:
  - kloudknoxpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - security.boanlab.com
  resources:
  - kloudknoxpolicies/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    boanlab.com/app: kloudknox-operator
  name: kloudknox-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kloudknox-operator-role
subjects:
- kind: ServiceAccount
  name: kloudknox-operator
  namespace: kloudknox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kloudknox-operator
  namespace: kloudknox
  labels:
    boanlab.com/app: kloudknox-operator
spec:
  selector:
    matchLabels:
      boanlab.com/app: kloudknox-operator
  replicas: 1
  template:
    metadata:
      labels:
        boanlab.com/app: kloudknox-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /kloudknox-operator
        args: []
        image: boanlab/kloudknox-operator:latest
        imagePullPolicy: IfNotPresent
        name: kloudknox-operator
        ports: []
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: kloudknox-operator
      terminationGracePeriodSeconds: 10
